[build]
  publish = "."
  functions = "netlify/functions"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200



[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Scheduled Functions
[functions."send-notifications"]
  schedule = "0 * * * *"

[dev]
  functions = "netlify/functions"
  publish = "."
  port = 8888

